trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

jobs:
- template: Source/DotNet/framework.yml@templates
  parameters:
    CASCADES: dolittle-runtime/DotNET.SDK