trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

jobs:
- template: Source/DotNet/pipeline.yml@templates
  parameters:
    CASCADES:
      - 'dolittle-extensions/ReadModels.MongoDB'
      - 'dolittle-runtime/Runtime.Events.MongoDB'
      - 'dolittle-runtime/Runtime.Events.EventStore'
      - 'dolittle-runtime/Runtime.Events.InMemory'
      - 'dolittle-runtime/Runtime.Events.Sqlite'
      - 'dolittle-runtime/Runtime.Events.Azure'
      - 'dolittle-runtime/DotNET.SDK'
      - 'dolittle-interaction/AspNetCore'
